export function error(err) {
  const resp = err.response;
  if (resp === undefined
    || resp.data === undefined
    || resp.data.error === undefined
    || resp.data.error.message === undefined) {
    return 'Unknown error';
  }
  return resp.data.error.message || 'server error';
}

// Router
export const ROUTER_SET_PATHNAME = 'ROUTER_SET_PATHNAME';

// Session
export const SESSION_SET_USER = 'SESSION_SET_USER';
export const GET_CURRENT_USER_REQUEST = 'GET_CURRENT_USER_REQUEST';
export const GET_CURRENT_USER_SUCCESS = 'GET_CURRENT_USER_SUCCESS';
export const GET_CURRENT_USER_FAILURE = 'GET_CURRENT_USER_FAILURE';
export const SESSION_SIGNIN = 'SESSION_SIGNIN';
export const SESSION_SIGNIN_SUCCESS = 'SESSION_SIGNIN_SUCCESS';
export const SESSION_SIGNIN_FAILURE = 'SESSION_SIGNIN_FAILURE';
export const SESSION_REGISTER = 'SESSION_REGISTER';
export const SESSION_REGISTER_SUCCESS = 'SESSION_REGISTER_SUCCESS';
export const SESSION_REGISTER_FAILURE = 'SESSION_REGISTER_FAILURE';

// Password Reset
export const RESET_PASSWORD = 'RESET_PASSWORD';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILURE = 'RESET_PASSWORD_FAILURE';
export const SET_NEW_PASSWORD = 'SET_NEW_PASSWORD';
export const SET_NEW_PASSWORD_SUCCESS = 'SET_NEW_PASSWORD_SUCCESS';
export const SET_NEW_PASSWORD_FAILURE = 'SET_NEW_PASSWORD_FAILURE';

// Brand
export const GET_BRANDS_REQUEST = 'GET_BRANDS_REQUEST';
export const GET_BRANDS_SUCCESS = 'GET_BRANDS_SUCCESS';
export const GET_BRANDS_FAILURE = 'GET_BRANDS_FAILURE';

// Category
export const GET_CATEGORIES_REQUEST = 'GET_CATEGORIES_REQUEST';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_FAILURE = 'GET_CATEGORIES_FAILURE';

// Product
export const GET_PRODUCTS_BY_CATEGORY_FILTER_REQUEST = 'GET_PRODUCTS_BY_FILTER_REQUEST';
export const GET_PRODUCTS_BY_CATEGORY_FILTER_SUCCESS = 'GET_PRODUCTS_BY_FILTER_SUCCESS';
export const GET_PRODUCTS_BY_CATEGORY_FILTER_FAILURE = 'GET_PRODUCTS_BY_FILTER_FAILURE';
export const GET_PRODUCTS_BY_FEATURED_REQUEST = 'GET_PRODUCTS_BY_FEATURED_REQUEST';
export const GET_PRODUCTS_BY_FEATURED_SUCCESS = 'GET_PRODUCTS_BY_FEATURED_SUCCESS';
export const GET_PRODUCTS_BY_FEATURED_FAILURE = 'GET_PRODUCTS_BY_FEATURED_FAILURE';
export const GET_PRODUCTS_BY_BRAND_REQUEST = 'GET_PRODUCTS_BY_BRAND_REQUEST';
export const GET_PRODUCTS_BY_BRAND_SUCCESS = 'GET_PRODUCTS_BY_BRAND_SUCCESS';
export const GET_PRODUCTS_BY_BRAND_FAILURE = 'GET_PRODUCTS_BY_BRAND_FAILURE';
export const GET_PRODUCTS_BY_CATEGORY_REQUEST = 'GET_PRODUCTS_BY_CATEGORY_REQUEST';
export const GET_PRODUCTS_BY_CATEGORY_SUCCESS = 'GET_PRODUCTS_BY_CATEGORY_SUCCESS';
export const GET_PRODUCTS_BY_CATEGORY_FAILURE = 'GET_PRODUCTS_BY_CATEGORY_FAILURE';
export const GET_PRODUCTS_BY_SEARCH_REQUEST = 'GET_PRODUCTS_BY_SEARCH_REQUEST';
export const GET_PRODUCTS_BY_SEARCH_SUCCESS = 'GET_PRODUCTS_BY_SEARCH_SUCCESS';
export const GET_PRODUCTS_BY_SEARCH_FAILURE = 'GET_PRODUCTS_BY_SEARCH_FAILURE';
export const GET_PRODUCTS_BY_FAVOURITES_REQUEST = 'GET_PRODUCTS_BY_FAVOURITES_REQUEST';
export const GET_PRODUCTS_BY_FAVOURITES_SUCCESS = 'GET_PRODUCTS_BY_FAVOURITES_SUCCESS';
export const GET_PRODUCTS_BY_FAVOURITES_FAILURE = 'GET_PRODUCTS_BY_FAVOURITES_FAILURE';
export const RESET_PRODUCTS_BY_CATEGORY = 'RESET_PRODUCTS_BY_CATEGORY';

// Search and Filters
export const SEARCH_PRODUCT_REQUEST = 'SEARCH_PRODUCT_REQUEST';
export const SEARCH_PRODUCT_SUCCESS = 'SEARCH_PRODUCT_SUCCESS';
export const SEARCH_PRODUCT_FAILURE = 'SEARCH_PRODUCT_FAILURE';
export const LOAD_MORE_PRODUCT_REQUEST = 'LOAD_MORE_PRODUCT_REQUEST';
export const LOAD_MORE_PRODUCT_SUCCESS = 'LOAD_MORE_PRODUCT_SUCCESS';
export const LOAD_MORE_PRODUCT_FAILURE = 'LOAD_MORE_PRODUCT_FAILURE';
export const SET_SUB_CATEGORY = 'SET_SUB_CATEGORY';
export const SET_COLORS = 'SET_COLORS';
export const SET_SIZES = 'SET_SIZES';
export const SET_SHOES_SIZES = 'SET_SHOES_SIZES';
export const SET_DESIGNERS = 'SET_DESIGNERS';
export const SET_BRANDS = 'SET_BRANDS';
export const SET_PRICES = 'SET_PRICES';
export const REMOVE_FILTERS = 'REMOVE_FILTERS';
export const REMOVE_SPECIFIC_FILTER = 'REMOVE_SPECIFIC_FILTER';

// Specific Filters
export const GET_BRAND_DESIGNERS_REQUEST = 'GET_BRAND_DESIGNERS_REQUEST';
export const GET_BRAND_DESIGNERS_SUCCESS = 'GET_BRAND_DESIGNERS_SUCCESS';
export const GET_BRAND_DESIGNERS_FAILURE = 'GET_BRAND_DESIGNERS_FAILURE';

// Trending
export const GET_TRENDING_REQUEST = 'GET_TRENDING_REQUEST';
export const GET_TRENDING_SUCCESS = 'GET_TRENDING_SUCCESS';
export const GET_TRENDING_FAILURE = 'GET_TRENDING_FAILURE';

// Admin
export const ADMIN_GET_PRODUCTS = 'ADMIN_GET_PRODUCTS';
export const ADMIN_GET_PRODUCTS_SUCCESS = 'ADMIN_GET_PRODUCTS_SUCCESS';
export const ADMIN_GET_PRODUCTS_FAILURE = 'ADMIN_GET_PRODUCTS_FAILURE';
export const ADMIN_SET_FEATURED = 'ADMIN_SET_FEATURED';
export const ADMIN_SET_FEATURED_SUCCESS = 'ADMIN_SET_FEATURED_SUCCESS';
export const ADMIN_SET_FEATURED_FAILURE = 'ADMIN_SET_FEATURED_FAILURE';
export const ADMIN_GET_SITES = 'ADMIN_GET_SITES';
export const ADMIN_GET_SITES_SUCCESS = 'ADMIN_GET_SITES_SUCCESS';
export const ADMIN_GET_SITES_FAILURE = 'ADMIN_GET_SITES_FAILURE';
export const ADMIN_UPDATE_SITE = 'ADMIN_UPDATE_SITE';
export const ADMIN_UPDATE_SITE_SUCCESS = 'ADMIN_UPDATE_SITE_SUCCESS';
export const ADMIN_UPDATE_SITE_FAILURE = 'ADMIN_UPDATE_SITE_FAILURE';
export const ADMIN_GET_CLICKS = 'ADMIN_GET_CLICKS';
export const ADMIN_GET_CLICKS_SUCCESS = 'ADMIN_GET_CLICKS_SUCCESS';
export const ADMIN_GET_CLICKS_FAILURE = 'ADMIN_GET_CLICKS_FAILURE';
export const ADMIN_GET_PRODUCTS_BY_APPROVED_STATUS = 'ADMIN_GET_PRODUCTS_BY_APPROVED_STATUS';
export const ADMIN_GET_PRODUCTS_BY_APPROVED_STATUS_REQUEST = 'ADMIN_GET_PRODUCTS_BY_APPROVED_STATUS_REQUEST';
export const ADMIN_GET_PRODUCTS_BY_APPROVED_STATUS_SUCCESS = 'ADMIN_GET_PRODUCTS_BY_APPROVED_STATUS_SUCCESS';
export const ADMIN_GET_PRODUCTS_BY_APPROVED_STATUS_FAILURE = 'ADMIN_GET_PRODUCTS_BY_APPROVED_STATUS_FAILURE';
export const ADMIN_EDIT_STATUS = 'ADMIN_EDIT_STATUS';
export const ADMIN_EDIT_STATUS_SUCCESS = 'ADMIN_EDIT_STATUS_SUCCESS';
export const ADMIN_EDIT_STATUS_FAILURE = 'ADMIN_EDIT_STATUS_FAILURE';
export const ADMIN_GET_PRODUCT_BY_ID = 'ADMIN_GET_PRODUCT_BY_ID';
export const ADMIN_GET_PRODUCT_BY_ID_SUCCESS = 'ADMIN_GET_PRODUCT_BY_ID_SUCCESS';
export const ADMIN_GET_PRODUCT_BY_ID_FAILURE = 'ADMIN_GET_PRODUCT_BY_ID_FAILURE';
export const ADMIN_UPDATE_PRODUCT_BY_ID = 'ADMIN_UPDATE_PRODUCT_BY_ID';
export const ADMIN_UPDATE_PRODUCT_BY_ID_SUCCESS = 'ADMIN_UPDATE_PRODUCT_BY_ID_SUCCESS';
export const ADMIN_UPDATE_PRODUCT_BY_ID_FAILURE = 'ADMIN_UPDATE_PRODUCT_BY_ID_FAILURE';
export const ADMIN_DELETE_PRODUCT_BY_ID = 'ADMIN_DELETE_PRODUCT_BY_ID';
export const ADMIN_DELETE_PRODUCT_BY_ID_SUCCESS = 'ADMIN_DELETE_PRODUCT_BY_ID_SUCCESS';
export const ADMIN_DELETE_PRODUCT_BY_ID_FAILURE = 'ADMIN_DELETE_PRODUCT_BY_ID_FAILURE';
export const ADMIN_DELETE_PRODUCTS_BY_ID = 'ADMIN_DELETE_PRODUCTS_BY_ID';
export const ADMIN_DELETE_PRODUCTS_BY_ID_SUCCESS = 'ADMIN_DELETE_PRODUCTS_BY_ID_SUCCESS';
export const ADMIN_DELETE_PRODUCTS_BY_ID_FAILURE = 'ADMIN_DELETE_PRODUCTS_BY_ID_FAILURE';
export const ADMIN_GET_USERS = 'ADMIN_GET_USERS';
export const ADMIN_GET_USERS_SUCCESS = 'ADMIN_GET_USERS_SUCCESS';
export const ADMIN_GET_USERS_FAILURE = 'ADMIN_GET_USERS_FAILURE';
export const ADMIN_SET_PERMISSION = 'ADMIN_SET_PERMISSION';
export const ADMIN_SET_PERMISSION_SUCCESS = 'ADMIN_SET_PERMISSION_SUCCESS';
export const ADMIN_SET_PERMISSION_FAILURE = 'ADMIN_SET_PERMISSION_FAILURE';
export const ADMIN_GET_PARTNER_SUMMARY = 'ADMIN_GET_PARTNER_SUMMARY';
export const ADMIN_GET_PARTNER_SUMMARY_SUCCESS = 'ADMIN_GET_PARTNER_SUMMARY_SUCCESS';
export const ADMIN_GET_PARTNER_SUMMARY_FAILURE = 'ADMIN_GET_PARTNER_SUMMARY_FAILURE';
export const ADMIN_GET_PARTNER_PRODUCT_SUMMARY = 'ADMIN_GET_PARTNER_PRODUCT_SUMMARY';
export const ADMIN_GET_PARTNER_PRODUCT_SUMMARY_SUCCESS = 'ADMIN_GET_PARTNER_PRODUCT_SUMMARY_SUCCESS';
export const ADMIN_GET_PARTNER_PRODUCT_SUMMARY_FAILURE = 'ADMIN_GET_PARTNER_PRODUCT_SUMMARY_FAILURE';
export const ADMIN_DELETE_SITE = 'ADMIN_DELETE_SITE';
export const ADMIN_DELETE_SITE_SUCCESS = 'ADMIN_DELETE_SITE_SUCCESS';
export const ADMIN_DELETE_SITE_FAILURE = 'ADMIN_DELETE_SITE_FAILURE';
